{% set name = "libsbml" %}
{% set version = "5.20.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/sbmlteam/libsbml/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 78d31fae25669dfa65d767ea3ff58ef95c9dcb4de7d8eac6f608cb6dbf5901c5

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('libsbml', max_pin='x.x') }}

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [not win]
    - ninja  # [win]
  host:
    - zlib
    - bzip2
    - libxml2

test:
  commands:
    - test -f "${PREFIX}/lib/libsbml${SHLIB_EXT-.so}"  # [linux]
    - test -f "${PREFIX}/lib/libsbml${SHLIB_EXT-.dylib}"  # [osx]    
    - if not exist %PREFIX%/Library/bin/libsbml.dll exit 1  # [win]
    - test -f "${PREFIX}/include/sbml/SBase.h"  # [not win]    
    - if not exist %PREFIX%/Library/include/sbml/SBase.h exit 1  # [win]
    - test -f "${PREFIX}/lib/cmake/sbml-config.cmake"  # [not win]
    - if not exist %PREFIX%/Library/lib/cmake/libsbml-config.cmake exit 1  # [win]
    - test -f "${PREFIX}/lib/pkgconfig/libsbml.pc"  # [not win]
about:
  home: http://sbml.org/software/libsbml/
  summary: 'Non-official conda package of libSBML with all available packages'
  description: |
    LibSBML is a free, open-source programming library to help you read, write, manipulate, translate, and validate SBML files and data streams.
    This is a non-official conda package of libSBML with all available packages, working for linux-64, linux-aarch64, osx-64, osx-arm64 and win-64. 
    This version was compiled with CPP namespace ON.

  license: LGPL-2.1-only
  license_family: LGPL

  license_file: LICENSE.txt

  doc_url: https://sbml.org/software/libsbml/libsbml-docs/api/c++/
  dev_url: https://github.com/sbmlteam/libsbml/

extra:
  recipe-maintainers:
    - vincent-noel
